# Generated by Django 5.1.4 on 2025-01-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_password_delete_cacheentry_alter_folder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
